### ISSUE TITLE
Dockerfile 构建的镜像跑步起来，报错

### ISSUE THREAD

**Issue by DongsGit** [zepen/predict_Lottery_ticket#26]
![image](https://user-images.githubusercontent.com/36791760/126606173-a6e08742-32a7-4e47-b7da-0208e8a6c93e.png)

**Comment by vinsonw** [comment]
同样的问题，好像运行成功过一次了，之后就一直报这个错误
![Snipaste_2021-07-23_01-30-07](https://user-images.githubusercontent.com/22071230/126682950-cf7d9501-a38a-4362-81fa-5dc3889f8c72.png)

**Comment by DongsGit** [comment]
> 同样的问题，好像运行成功过一次了，之后就一直报这个错误
> ![Snipaste_2021-07-23_01-30-07](https://user-images.githubusercontent.com/22071230/126682950-cf7d9501-a38a-4362-81fa-5dc3889f8c72.png)
本地跑吧，本地我跑起来了，在windows跑还要注意有个报错

**Comment by vinsonw** [comment]
> 同样的问题，好像运行成功过一次了，之后就一直报这个错误
> ![Snipaste_2021-07-23_01-30-07](https://user-images.githubusercontent.com/22071230/126682950-cf7d9501-a38a-4362-81fa-5dc3889f8c72.png)
> 本地跑吧，本地我跑起来了，在windows跑还要注意有个报错

Windows上装docker还是算了，我改用excel预测了哈哈

**Comment by DongsGit** [comment]
不是windows装docker啊，是代码在windows跑

**Comment by DongsGit** [comment]
> > 同样的问题，好像运行成功过一次了，之后就一直报这个错误
> > ![Snipaste_2021-07-23_01-30-07](https://user-images.githubusercontent.com/22071230/126682950-cf7d9501-a38a-4362-81fa-5dc3889f8c72.png)
> > 本地跑吧，本地我跑起来了，在windows跑还要注意有个报错
> 
> Windows上装docker还是算了，我改用excel预测了哈哈

不是windows装docker啊，是代码在windows跑

**Comment by vinsonw** [comment]
在cmd里面跑吗，还是在wsl 里面，后者我之前试了一下, tensorflow版本装不上 ---- 回复的原邮件 ***@***.***>发送日期2021年07月23日 17:01 ***@***.***> ***@***.******@***.***>主题Re: [zepen/predict_Lottery_ticket] Dockerfile 构建的镜像跑步起来，报错 (#26)

不是windows装docker啊，是代码在windows跑



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/zepen/predict_Lottery_ticket/issues/26#issuecomment-885500119",

"url": "https://github.com/zepen/predict_Lottery_ticket/issues/26#issuecomment-885500119",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by vinsonw** [comment]
> > > 同样的问题，好像运行成功过一次了，之后就一直报这个错误
> > > ![Snipaste_2021-07-23_01-30-07](https://user-images.githubusercontent.com/22071230/126682950-cf7d9501-a38a-4362-81fa-5dc3889f8c72.png)
> > > 本地跑吧，本地我跑起来了，在windows跑还要注意有个报错
> > 
> > 
> > Windows上装docker还是算了，我改用excel预测了哈哈
> 
> 不是windows装docker啊，是代码在windows跑

![Snipaste_2021-07-23_22-16-31](https://user-images.githubusercontent.com/22071230/126795236-20bdda12-fb11-44dd-87a1-bfbe55bab6e0.png)
不知道为什么又跑起来了，之前报错tf的版本不对，thx

**Comment by zepen** [comment]
这里配置文件没写对，修复了这个问题，应该可以docker build . 一键部署了
